### PR TITLE
Vegeta Benchmark

### PR DESCRIPTION
**Pull request by baerdal**
Adding vegeta benchmark with many of the indices included at https://github.com/cloud-bulldozer/snafu/pull/190

### CODE REVIEW

**Comment by baerdal** [comment]
Sample run and output:
Screenshot from 2020-06-25 14-26-33

**Comment by rsevilla87** [comment]
Hey @baerdal, @jtaleric added some new metrics, can also you include them? https://github.com/cloud-bulldozer/snafu/blob/master/vegeta_wrapper/trigger_vegeta.py#L94-L98

Thanks in advance

**Comment by jtaleric** [comment]
I haven't tested this yet, but I am curious, do we aggregate on all targets per UUID? Do we assume all the targets are the same?

**Comment by baerdal** [comment]
I believe we aggregate on all targets per UUID, and we don't assume that all targets are the same. Once Marquez comes back up I'll test and know for sure.

**Comment by rsevilla87** [comment]
Hey @baerdal, can you update docs to include this test?

**Pull request merged**
